### ISSUE TITLE
editor

### ISSUE THREAD

**Issue by sytzemeijer** [queso-fuego/amateuros#2]
how can I run the editor. When I type `editor` it doesn't work (even if i type `editor.bin`)

**Comment by queso-fuego** [comment]
It's not going to work right now, until there are more changes for the newer filesystem and syscalls.
Probably need to use open() and then call/execute the address it would be loaded to in the open file table.

Something like this in the kernel:
int fd = open("editor.bin");
open_file_table_t *oft = open_file_table + fd;
int (*program)(int argc, char *argv[]) = oft->address;
int return_code = program(argc, argv);

I should get to this after read()/write() syscalls are more implemented, hopefully in the next week or two.

**Comment by sytzemeijer** [comment]
Ok, thanks
